import {
  Bag,
  Pizza,
  DotsThreeVertical,
  Gear,
  Notepad,
  Plus,
  Brandy,
  Hamburger,
  CirclesThree,
  Trash,
  PencilSimpleLine,
  Warning,
  FloppyDisk,
  CaretDown,
  User,
  ToteSimple,
  MagnifyingGlass,
  Money,
  Moped,
  XCircle,
  CaretLeft,
  Storefront,
  MapPin,
  Files,
  SignOut,
} from "@phosphor-icons/react";

export const DefaultIcons = {
  ProductIcon: Bag,
  ConfigurationIcon: Gear,
  DeliveryIcon: Moped,
  CardapioIcon: Notepad,
  AddIcon: Plus,
  PizzaIcon: Pizza,
  DrinkIcon: Brandy,
  FoodIcon: Hamburger,
  OutrosIcon: CirclesThree,
  MoreIcon: DotsThreeVertical,
  DeleteIcon: Trash,
  EditIcon: PencilSimpleLine,
  WarningIcon: Warning,
  SaveIcon: FloppyDisk,
  EntregadorIcon: User,
  CaretDownIcon: CaretDown,
  AccountIcon: User,
  CartIcon: ToteSimple,
  SearchIcon: MagnifyingGlass,
  SignInIcon: User,
  MoneyIcon: Money,
  CancelIcon: XCircle,
  BackIcon: CaretLeft,
  EmpresaIcon: Storefront,
  BairroIcon: MapPin,
  NFCeIcon: Files,
  ExitIcon: SignOut,
};
